name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install npm dependencies
        run: npm install
      - name: npm init
        run: npm init -y
      - name: Run build task
        run: npm run build --if-present
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-avz --delete"
          REMOTE_HOST: ns3044267.siegler-informatique.fr
          REMOTE_PORT: 61212
          REMOTE_USER: sebastienserre
          TARGET: /var/www/sme/wp-content/plugins/thfo-intranet
          EXCLUDE: "/.git, /.github, /dist/, /node_modules/, /languages, /plugins, /theme-css, /uploads, /wpgb, db.php,
          index.php"